name: power_plan_fe
description: "A training app which gets you to ne next level"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5
  http: ^1.4.0
  supabase_flutter: ^2.9.1
